name: Telegram Bot Test

on:
  workflow_dispatch:  # para ejecutarlo manualmente desde Actions

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚀 Hola Juanjo, tu bot ya está funcionando desde GitHub Actions!"
